spring:
  datasource:
    url: 'jdbc:mysql://${base.db.address:118.31.6.137:3306}/demo?allowMultiQueries=true&zeroDateTimeBehavior=convertToNull&characterEncoding=UTF-8'
    username: 'root'
    password: '123456'
    driver-class-name: com.mysql.cj.jdbc.Driver